---
title: 'Introduction'
---
  
  This project seeks to find whether areial ability is affected by a football player's height.
 
  Although tall strikers in the premier league have often been valued for their aerial finesse (Peter Crouch, Andy Carroll to name a few), there has been no statistical analysis proving this relationship. 
  
  Being an avid fan myself, I was curious to find whether this is necessary the case at such a high level of professional football. This analytical piece should also provide evidence as to whether clubs should consider paying and charging a premium for taller players. By categorizing them into categories, by position, I will be able to see whether this relationship between height and ability to win headers is a general relationship or one that is more specific to the position of the players. (defenders, midfielders, strikers) In this way I will also be able to provide evidence as to whether this premium stretches beyond strikers.
  
  
  
  Research Hypothesis:
  
  Catergorized by their positions, a player's height will increase his % of headers won.
  
  H0:
  Catergorized by their positions, a player's height does not affect the % of headers won.